### ISSUE TITLE
java.lang.ClassNotFoundException: org.springframework.data.repository.core.support.ReflectionEntityInformation

### ISSUE THREAD

**Issue by mianqiangsheng** [michaellavelle/spring-data-dynamodb#100]
When my project is based on spring-data-commons 2.2.6，while spring-data-dynamodb is based on spring-data-commons 2.1.2 which does not contain ReflectionEntityInformation.class then my project can't start. How can I fix this problem?

**Comment by boostchicken** [comment]
Hey @mianqiangsheng, 
Development happens [here ](https://github.com/boostchicken/spring-data-dynamodb) now
