### ISSUE TITLE
Can you please publish a release version

### ISSUE THREAD

**Issue by mbyrne00** [michaellavelle/spring-data-dynamodb#36]
First, thanks for the project - very handy.

I understand this is still a work in progress but is there any chance you could publish a RELEASE version, even if it's just to your own repository? That way we can have a static RELEASE version dependency on what's done so far.

**Comment by derjust** [comment]
A current release is available at http://search.maven.org/#artifactdetails%7Ccom.github.derjust%7Cspring-data-dynamodb%7C4.2.0%7Cjar - 4.2.0 is equal to the old 1.0.3-SNAPSHOT but follows a more spring-data related version schema.
As (privately) communicated with @michaellavelle, the project will continue under https://github.com/derjust/spring-data-dynamodb/issues/12.
