### ISSUE TITLE
SimpleDynamoDBCrudRepository.findAll(java.lang.Iterable<ID>) does not working

### ISSUE THREAD

**Issue by tpenakov** [michaellavelle/spring-data-dynamodb#40]
SimpleDynamoDBCrudRepository.findAll(java.lang.Iterable<ID>) is receiveing map result from dynamoDBOperations. The problem is that it tried to retrieve the list with result through key based on domainType. The actual map keys retyrned from dynamoDBOperations are based on dynamodb table name.

**Comment by derjust** [comment]
Tested the PR https://github.com/michaellavelle/spring-data-dynamodb/pull/41 which seems to work. Unsure about the discussion in the PR itself.

**Comment by michaellavelle** [comment]
The suggested fixes have now been implemented in latest snapshot build - many thanks
