### ISSUE TITLE
Attributes names in DynamoDBRepositoryConfigExtension not compliant with schema definition

### ISSUE THREAD

**Issue by sirjasiu** [michaellavelle/spring-data-dynamodb#45]
In scema (spring-dynamodb-1.0.xsd) the following attributes are supported:
amazon-dynamodb-ref
dynamodb-mapper-config-ref
dynamodb-operations-ref

while in DynamoDBRepositoryConfigExtension atributes used for getting bean in postProcess(.., XMLRepositoryConsigurationSource) method are:
amazon-dynamodb-ref (AMAZON_DYNAMODB_REF)
dynamoDBMapperConfig (DYNAMO_DB_MAPPER_CONFIG_REF)
dynamoDBOperations (DYNAMO_DB_OPERATIONS_REF)

Because of this it is impossible to define own mapperConfig or operations in xml.

**Comment by derjust** [comment]
Check out https://github.com/derjust/spring-data-dynamodb/commit/7a626e78f13a710ef939d26f4c3652d587bd2281 - in recent versions of spring-data-dynamodb the XSD is correct
