### ISSUE TITLE
Does this module require the entire aws-sdk as a dependency ?

### ISSUE THREAD

**Issue by srekapalli** [michaellavelle/spring-data-dynamodb#51]
Pom refers to com.amazonaws:aws-java-sdk:1.9.0 and it is pulling lot of other SDK's libs in to the war. Not sure whether we need all or we can exclude..?

**Comment by michaellavelle** [comment]
Good question... I hadn't realised that the dependency was pulling in all those extra libs.

I just had a look into this and I think that the dependency may be able to be modified to "aws-java-sdk-dynamodb" from the "aws-java-sdk" dependency as it is now.

The code compiles with this change, the tests pass, but I'm not in the position to try this out against a real dynamodb instance as I write this -  perhaps you might be a position to give it a go and let me know if it works?

Thanks for raising this - will make dependency management much easier if this can be done.

Cheers,

Michael

**Comment by igilham** [comment]
I have made the same change to a completely different codebase before and had no problems with a real database or a DynamoDB Local instance (via jcabi plugin). The AWS libraries are packaged correctly with all required dependencies as far as I can tell.

I don't suggest skipping the testing step, but I believe the change will work without issue.

**Comment by derjust** [comment]
Also tested here with dedicated `excludes` in my `pom.xml`. Seems to work for our code paths.
