### ISSUE TITLE
Compatibility with spring-data-rest

### ISSUE THREAD

**Issue by derjust** [michaellavelle/spring-data-dynamodb#57]
Hi!
Thanks for this project!

I tried to integrate it with spring-data-rest to expose my entities. It worked quite well with minor adoptions:
- Major bummer is that `org.springframework.data.rest.webmvc.config.RepositoryRestMvcConfiguration.persistentEntities()` searches for `MappingContext`s whereas the `DynamoDBMappingContext` is created with `new` in `org.socialsignin.spring.data.dynamodb.repository.support.DynamoDBRepositoryFactoryBean<T, S, ID>`
- Second problem is that `org.socialsignin.spring.data.dynamodb.mapping.DynamoDBMappingContext.hasPersistentEntityFor(Class<?>)` always returns false before a class is manually added.

To workaround those two problems, I added to my own `ConfigurationBean` the following code:

``` java
    @Bean
    public DynamoDBMappingContext getMappingContext() {
        DynamoDBMappingContext context = new DynamoDBMappingContext();

        context.getPersistentEntity(MyDynamoDBTable.class);

        return context;
    }
```

I can't really judge if that is cleaver because that leads to multiple `DynamoDBContext`s floating around but as they are usually only delegating to another constructor that seems fine to me.

Is there a better way to do it?
Can this somehow be incorporated into the library itself so that it is out-of-the-box Spring-Boot compatible?

Used versions:
- Spring Boot 1.2.3.RELEASE
- spring-data-dynamodb 1.0.1.RELEASE
- spring-boot-starter-data-rest 1.2.3.RELEASE

**Comment by Selindek** [comment]
I had the same problem although I found a different solution. I manually exposed the existing MappingContext from the DynamoDBRepositoryFactoryBean:

	
	@SuppressWarnings("rawtypes")
	@Autowired
	private DynamoDBRepositoryFactoryBean dynamoDBRepositoryFactoryBean;

	@Bean
	public MappingContext<?, ?> getPrivateDynamoDbMappingContext(){
		return (MappingContext<?, ?>)FieldUtils.getProtectedFieldValue("mappingContext", dynamoDBRepositoryFactoryBean);
	}

Not the best solution either, but it works. (And if the DynamoDBMappingContext changes by any reason later, it will still work.)

**Comment by wnagele** [comment]
Without this - PUT requests won't work to update entities. I think this is a bug in the current implementation and needs adressing. I used the solution from @Selindek to work around it as well.
