### ISSUE TITLE
Library repository unavailable

### ISSUE THREAD

**Issue by ryonday** [michaellavelle/spring-data-dynamodb#58]
It would appear that the Maven repository you have listed for the library http://repo.opensourceagility.com/release is down. 

We are preparing to use this library for a production effort; we're more than happy to fork and contribute to the code base.

**Comment by michaellavelle** [comment]
Hi

I've just checked the repo and it seems to be working now.   The url should redirect to the location of the hosted libs - if you add a trailing slash to the url this works for me.

 http://repo.opensourceagility.com/release/

Hope this helps,

Cheers,

Michael

**Comment by JuanCarlosGonzalez** [comment]
Hi Michael.

I really like this project, but I'm experiencing the same problem mentioned above. Looks like there is some issue with the maven repo as the artifact cannot be resolved.

**Comment by JuanCarlosGonzalez** [comment]
Hi again.

Looks like the jars are not properly deployed to the repo. The problem in not the url, but the deployment. I can see in my local repo entries for versions 1.0.1, 1.0.2 and 1.0.3, but all of them contain .lastUpdated pom and jar files.

**Comment by derjust** [comment]
Worked here.
To my experience, `.lastUpdated` sometimes confuses m2e. Removing those files manually and running a `mvn` again solves it for me.

**Comment by JuanCarlosGonzalez** [comment]
Thanks for the hint and sorry for a so trivial question.
