### ISSUE TITLE
Pass in table name via context or environment variable

### ISSUE THREAD

**Issue by ujjwal** [michaellavelle/spring-data-dynamodb#65]
```
@DynamoDBTable(tableName = "someTableName")
```

Is there a way to pass the tableName as a parameter?

**Comment by dustinmoris** [comment]
I had the same question, but this helped me to resolve all my requirements:
https://blogs.aws.amazon.com/net/post/Tx2C4MHH2H0SA5W/Enhancements-to-the-DynamoDB-SDK

**Comment by derjust** [comment]
Yes via AWS functionality itself:

```
@Configuration
@EnableDynamoDBRepositories(dynamoDBMapperConfigRef = "dynamoDBMapperConfig",
    basePackages = "com.acme.repository")
public class DynamoDBConfig {
    @Bean
    public DynamoDBMapperConfig dynamoDBMapperConfig() {
        DynamoDBMapperConfig.Builder builder = new DynamoDBMapperConfig.Builder();
        builder.setTableNameResolver(new YourCustomTableNameResolverHere());
        return builder.build();
    }
}

If you just wan to prefix table names (to separate environments), there are ready-to go classes:
```
        builder.setTableOverride(com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperConfig.TableNameOverride.withTableNamePrefix(dbPrefix));
```

**Comment by derjust** [comment]
Please let us know if the provided answer helps your use case. Please use https://github.com/derjust/spring-data-dynamodb/issues/18 for followup comments.

As (privately) communicated with @michaellavelle, the project will continue under https://github.com/derjust/spring-data-dynamodb.

**Comment by derjust** [comment]
Check out https://github.com/derjust/spring-data-dynamodb/wiki/Alter-table-name-during-runtime

**Comment by AliakseiMat** [comment]
Not sure maybe it is the bug in AWS lib. I'm using "aws-java-sdk-bom" 1.11.175. The problem is when I use my own DynamoDBMapperConfig, then config.getTypeConverterFactory() is the null and internal error thrown.  
I have added:
builder.setTypeConverterFactory(DynamoDBMapperConfig.DEFAULT.getTypeConverterFactory());
