### ISSUE TITLE
http://repo.opensourceagility.com domain has been parked 

### ISSUE THREAD

**Issue by archie-sh** [michaellavelle/spring-data-dynamodb#67]
http://repo.opensourceagility.com/release has been parked and its not possible to download the jar with maven

**Comment by michaellavelle** [comment]
Hi

If you add a trailing slash to the url, you should get the correct redirect:

http://repo.opensourceagility.com/release/ 

Thanks,

Michael

**Comment by archie-sh** [comment]
Hi, it would be nice if you updated the readme.d with the slash

**Comment by michaellavelle** [comment]
Sure - just changed the url in the readme - thanks for bringing this to my attention.

Cheers,

Michael

**Comment by brunocalmon** [comment]
Hey fellow,
 Could not GET 'http://repo.opensourceagility.com/release/org/socialsignin/spring-data-dynamodb/4.2.1/spring-data-dynamodb-4.2.1.pom' have you dropped the project or there's anywhere else to find it?
