### ISSUE TITLE
Updated User.java example

### ISSUE THREAD

**Issue by ascooper57** [michaellavelle/spring-data-dynamodb#69]
package org.socialsignin.springframework.data.dynamodb.demo.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import org.springframework.data.annotation.Id;

@DynamoDBTable(tableName = "User")
public class User {

```
@Id
private String idHashKey;
private String firstName;
private String lastName;

public User(String firstName, String lastName) {
    this.firstName = firstName;
    this.lastName = lastName;
}

public User() {}

@DynamoDBHashKey(attributeName = "IdHashKey")
@DynamoDBAutoGeneratedKey
public String getIdHashKey()
{
    return idHashKey;
}

public void setIdHashKey(String idHashKey) {
    this.idHashKey = idHashKey;
}

@DynamoDBAttribute(attributeName = "FirstName")
public String getFirstName()
{
    return firstName;
}

public void setFirstName(String firstName) {
    this.firstName = firstName;
}

@DynamoDBAttribute(attributeName = "LastName")
public String getLastName()
{
    return lastName;
}

public void setLastName(String lastName) {
    this.lastName = lastName;
}
```

}

**Comment by derjust** [comment]
What exactly does this new unit test code helps for? Please use derjust#20 for followup comments.

As (privately) communicated with @michaellavelle, the project will continue under https://github.com/derjust/spring-data-dynamodb.
