### ISSUE TITLE
Gradle package

### ISSUE THREAD

**Issue by Deepak-rzt** [michaellavelle/spring-data-dynamodb#70]
Hi,
Thanks for publishing this. Is there a gradle package submitted so that I can pull it from the gradle repositories?

**Comment by zapl** [comment]
Gradle uses maven repositories. There is no need for a separate gradle package. The following needs to be added to `build.gradle`

```
repositories {
    ... // there is probably maven central here
    maven {
        // for spring-data-dynamodb
        url "http://repo.opensourceagility.com/release"
    }
}

dependencies {
    ... // all the other spring dependencies
    compile 'org.socialsignin:spring-data-dynamodb:1.0.2.RELEASE'
    ...
}
```

That's equivalent to the following maven config
```
<repository>
    <id>opensourceagility-release</id>
    <url>http://repo.opensourceagility.com/release/</url
</repository>

<dependency>
  <groupId>org.socialsignin</groupId>
  <artifactId>spring-data-dynamodb</artifactId>
  <version>1.0.2.RELEASE</version>
</dependency>
```

**Comment by derjust** [comment]
A current release is available at http://search.maven.org/#artifactdetails%7Ccom.github.derjust%7Cspring-data-dynamodb%7C4.2.0%7Cjar - 4.2.0 is equal to the old 1.0.3-SNAPSHOT but follows a more spring-data related version schema.
As (privately) communicated with @michaellavelle, the project will continue under derjust#21.
