### ISSUE TITLE
Not compatible with Spring Boot 1.3

### ISSUE THREAD

**Issue by thomasturrell** [michaellavelle/spring-data-dynamodb#71]
spring-data-dynamodb Version 1.0.2 isn't compatible with Spring Boot 1.3. Spring Boot 1.3 was released on the 15th of November 2016.

spring-data-dynamodb is really useful to me, I hope it's updated to support Spring Boot 1.3.

**Comment by derjust** [comment]
What is the issue you see?
I'm using it with Spring Boot 1.2 right now and had an upgrade to 1.3 on my list.

**Comment by thomasturrell** [comment]
this pull request seems relevant https://github.com/michaellavelle/spring-data-dynamodb/pull/66

**Comment by derjust** [comment]
Issue solved via #72 

As (privately) communicated with @michaellavelle, the project will continue under https://github.com/derjust/spring-data-dynamodb.
