### ISSUE TITLE
spring-data-dynamodb:1.0.2.RELEASE does not work with spring boot 1.3.0.RELEASE.

### ISSUE THREAD

**Issue by czmatsunaga-naoko** [michaellavelle/spring-data-dynamodb#72]
spring-data-dynamodb:1.0.2.RELEASE does not work with spring boot 1.3.0.RELEASE.

When using with Spring boot 1.3.0.RELEASE, I got a runtime error like below.
An initialization of a class extended CrudRepository is failed, then nested exception occurs.
When using with Spring boot 1.2.7.RELEASE, it does not happen.

Please fix it, 
or please tell me the way to fix.

```
nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepository': Invocation of init method failed; nested exception is java.lang.AbstractMethodError: org.springframework.data.repository.core.support.RepositoryFactorySupport.getTargetRepository(Lorg/springframework/data/repository/core/RepositoryInformation;)Ljava/lang/Object;
```

**Comment by derjust** [comment]
Grab https://github.com/michaellavelle/spring-data-dynamodb/pull/73 and build it locally ('mvn install') and let us know if that works (Most of the street credz goes to @theonlyguills

**Comment by czmatsunaga-naoko** [comment]
I tried #73 and it works fine!
thnx for fixing :)
so please let us be able to use #73 from http://repo.opensourceagility.com/release

**Comment by derjust** [comment]
Thanks for the feedback @czmatsunaga-naoko.
Absolutely want to see it also at http://repo.opensourceagility.com/release but that's to be done by @michaellavelle, the project owner/author.

**Comment by jdhankins** [comment]
Confirmed that #73 works.  Thanks.

**Comment by derjust** [comment]
https://search.maven.org/#search%7Cga%7C1%7Ccom.github.derjust - Hopefully we can merge that back here somewhen.

**Comment by derjust** [comment]
As (privately) communicated with @michaellavelle, the project will continue under https://github.com/derjust/spring-data-dynamodb.

**Comment by czmatsunaga-naoko** [comment]
@derjust Thanx, again.
