### ISSUE TITLE
Dynamically change value of DynamoDBTable

### ISSUE THREAD

**Issue by maksimu** [michaellavelle/spring-data-dynamodb#77]
I have three different environments (dev, stage, and prod) and for each environment I would like to change the value of the `tableName` in `@DynamoDBTable`.

In other words based on my profile the following need to be changed `@DynamoDBTable(tableName="dynamic-value")`

What would be the best approach to tackle this situation?

**Comment by vkea95** [comment]
I have the same problem. And I don't think there is a solution.
And there is a the other solution for DyanmoDB, but I have to give up spring-data-dynamodb at first.
https://www.jayway.com/2013/10/09/dynamic-table-name-in-dynamodb-with-java-dynamomapper/
