### ISSUE TITLE
Querying on Complex Object Attributes

### ISSUE THREAD

**Issue by ravichauhan03** [michaellavelle/spring-data-dynamodb#85]
Hi,

I think the query on Complex Member is not available.

For e.g.:
Class SubA{
    private String name;
    private String value;
}
Class A{
   private List<SubA> list;
   private Id;
}

Now If i wanted to query on name field of Sub A how can I do this ?

**Comment by ravichauhan03** [comment]
Also Can you please tell me if I need to query for findById(List<String> ids) ?? what can be done ?

**Comment by EvanCoh** [comment]
take a look at
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.ArbitraryDataMapping.html

I think this is what you mean.

**Comment by derjust** [comment]
> Regarding `findById(List ids)`:

For the Spring-Data query builder to respect the list you have to use

```java
findByIdIn(List ids) 
```
see also [Issue #84](https://github.com/spring-data-dynamodb/spring-data-dynamodb/issues/84) and this [wiki](https://github.com/spring-data-dynamodb/spring-data-dynamodb/wiki/Supported-Spring-Data-Comparison-Operators).
