### ISSUE TITLE
Table name prefix solution in spring-data-dynamodb

### ISSUE THREAD

**Issue by ravichauhan03** [michaellavelle/spring-data-dynamodb#91]
We are using spring data dynamodb dependency in our project and initial development was fast. But, not we wanted to have different table prefixes for different environments like dev, stag, prod etc. Can you please support this feature?

**Comment by derjust** [comment]
Hi!
The development of this project happens now [here](https://github.com/derjust/spring-data-dynamodb)

Your requested feature is documented in the wiki article [Alter table name during runtime](https://github.com/derjust/spring-data-dynamodb/wiki/Alter-table-name-during-runtime).
