### ISSUE TITLE
Jpa Hitting performance impact it internally uses scan operation

### ISSUE THREAD

**Issue by jitendra-maurya0** [michaellavelle/spring-data-dynamodb#93]
What @EnableScan does there is no documentation. it seems like it hitting performance impact of dynamo db Using this getting ProvisionedThroughPutExceededExcecption.  @derjust  is there any better way to query records instead of scan. If you have any suggestion please guide me.

**Comment by derjust** [comment]
Hi @Cybertran !
The development of this project happens now [here](https://github.com/derjust/spring-data-dynamodb)

It sounds a bit strange that a `Scan` is hitting the `ProvisionedThrough**Put**ExceededExcecption`.
`@EnableScan` is a marker annotation to allow a method to use a `Scan` operation - as it is expensive and scans the whole table.

You should create GSIs and perform `Query`s:
* GSI [explained](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GSI.html) 
* GSI [example](https://github.com/derjust/spring-data-dynamodb/wiki/DynamoDB-GSI-Example) in the new project's wiki
